### ISSUE TITLE
[JOSS REVIEW] Elaborate on applications

### ISSUE THREAD

**Issue by finsberg** [CastillonMiguel/phasefieldx#10]
In your paper you mention some relevant applications. I think it would be good to give some more details about the applications and perhaps also add some figures showing the results of the simualtions using your software.

This issue is related to the review here: https://github.com/openjournals/joss-reviews/issues/7307

**Comment by CastillonMiguel** [comment]
The changes have been committed and are now reflected in the updated version of the paper.

https://github.com/CastillonMiguel/phasefieldx/commit/487b67af6c257d0bf032dd8f01234dbc184ac4e1
