### ISSUE TITLE
[JOSS REVIEW] Compare your software with other commonly-used packages 

### ISSUE THREAD

**Issue by finsberg** [CastillonMiguel/phasefieldx#6]
According to the [Review criteria](https://joss.readthedocs.io/en/latest/review_criteria.html#the-joss-paper), the paper should contain *A description of how this software compares to other commonly-used packages in this research area*. I don't see such a comparison in your paper. 

This issue is related to the review here: https://github.com/openjournals/joss-reviews/issues/7307

**Comment by CastillonMiguel** [comment]
The changes have been committed and are now reflected in the updated version of the paper.

https://github.com/CastillonMiguel/phasefieldx/commit/487b67af6c257d0bf032dd8f01234dbc184ac4e1

**Comment by finsberg** [comment]
Thanks. This look much better :)  However, I still think you need to write a little bit about how your software compares with other commonly-used packages. Here are some that I found when searching online

- https://github.com/prisms-center/phaseField
- https://github.com/SoftSimu/SymPhas
- https://github.com/micmog/CIPHER
- https://mooseframework.inl.gov/modules/phase_field/
- https://openphase.rub.de
- https://www.micress.de
- maybe others?

It should be noted, that I am not an expert in phase field modeling and don't know it these softwares can be compared directly with your software.

**Comment by CastillonMiguel** [comment]
Thanks for providing all these references. I would like to clarify that, at the moment, the main focus of the PhaseFieldX package is on phase field fracture and fatigue models, and the comparisons I have made in the paper are based on these aspects.

However, the package does include a simple model related to the Allen-Cahn equation, which can be compared to some of the references you provided. I can add a comment on this part in the paper.

**Comment by CastillonMiguel** [comment]
I added some of the references you suggested, and I also added some related to phase-field fracture simulation (the Raccoon GitHub repository https://github.com/hugary1995/raccoon ). I also made some minor changes to the paper. I updated the JOSS paper in the commit https://github.com/CastillonMiguel/phasefieldx/commit/0ecf1f6d128da74a8c06109278a064499e1dd13b, and the paper was also generated by GitHub Actions in: https://github.com/CastillonMiguel/phasefieldx/actions/workflows/build_joss_paper.yml
