### ISSUE TITLE
[JOSS REVIEW] Improve description in examples

### ISSUE THREAD

**Issue by finsberg** [CastillonMiguel/phasefieldx#9]
I must first say that I really like the way you have created the examples. It is really cool with both the pyvista integration and the "Download buttons" at the end. Really nice job!

I think however that some of the examples could be improved by providing some more text explaining the different examples, preferable with the necessary mathematical background and references to papers. For example in [Displacement control](https://phasefieldx.readthedocs.io/en/latest/auto_examples/Elasticity/plot_1100.html#sphx-glr-auto-examples-elasticity-plot-1100-py) there are not really any text explaining what this example is about, and it seems to be some headings and text that are copy-pasted from other examples. 

Instead of creating a separate issue for each example I create this one as a general issue for all of them, and then you can go through the examples and make sure that each example reads as a coherent piece of text. 

This issue is related to the review here: https://github.com/openjournals/joss-reviews/issues/7307

**Comment by CastillonMiguel** [comment]
I’m currently working on revising the examples and adding more detailed text, including necessary references and a clearer explanation of each example's purpose.
To keep track of the progress, I’m planning to address each examples section , and here’s a list of sections that I’ve revised or am working on revising:

* ~~AllenCahn:~~ https://github.com/CastillonMiguel/phasefieldx/commit/823c48c481359e67fab5b68e4f811855d2619005
* ~~Elasticity:~~ https://github.com/CastillonMiguel/phasefieldx/commit/6308f86429a04a94abc898a2a93a1f3fe1cb5f43
* Fatigue
* GmshGeoFiles
* ~~PhaseField:~~ https://github.com/CastillonMiguel/phasefieldx/commit/e79cd38ed7d23015ef0629e1300b06558a21d880
* PhaseFieldFracture

I’ll update the examples to ensure they form coherent, self-contained explanations.
Thanks again for your input!

**Comment by finsberg** [comment]
Looks very good! A few minor things
- The plot at the end [here](https://phasefieldx.readthedocs.io/en/latest/auto_examples/PhaseField/plot_2000.html) is not showing.
- Some text on [this page](https://phasefieldx.readthedocs.io/en/latest/auto_examples/PhaseFieldFracture/plot_1714.html#boundary-conditions) looks now well formatted.

**Comment by CastillonMiguel** [comment]
Thanks for the feedback! I’ve resolved the plot display issue and improved text formatting in that file and across other related files for better readability
